SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

DROP SCHEMA IF EXISTS `prescription`;
CREATE SCHEMA IF NOT EXISTS `prescription` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `prescription`;

DROP TABLE IF EXISTS `prescriptions`;
CREATE TABLE `prescriptions` (
  `date` date DEFAULT NULL,
  `orderID` int NOT NULL,  
  `price` decimal(10,2) DEFAULT NULL,
  `status` varchar(90) DEFAULT NULL,
  PRIMARY KEY (`orderID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `prescriptions` (`date`, `orderID`, `price`, `status`) VALUES 
('2015-03-20', 123, 100, 'Make Payment');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
